func testLinkedListSet() {
    print("-----test LinkedListSet-----")
    let setA = LinkedListSet<Int>()
    let setB = LinkedListSet<Int>(0)
    let setC = LinkedListSet<Int>([1,2,3])
    let setD = LinkedListSet<Int>([1,2,2,2,3])
    print(setA.isEmpty)
    print(setA.size)
    print(setB.isEmpty)
    print(setB.size)
    print(setC.isEmpty)
    print(setC.size)
    print(setD.isEmpty)
    print(setD.size)
    setD.remove(1)
    setD.remove(3)
    setD.remove(2)
    print("After remove \(setD.size)")
    setD.add(10)
    setD.add(20)
    print("After add \(setD.size)")
}


func testBSTSet() {
    print("-----test BSTSet-----")
    let setA = BSTSet<Int>()
    let setB = BSTSet<Int>(0)
    let setC = BSTSet<Int>([1,2,3])
    let setD = BSTSet<Int>([1,2,2,2,3])
    print(setA.isEmpty)
    print(setA.size)
    print(setB.isEmpty)
    print(setB.size)
    print(setC.isEmpty)
    print(setC.size)
    print(setD.isEmpty)
    print(setD.size)
    setD.remove(1)
    setD.remove(3)
    setD.remove(2)
    print("After remove \(setD.size)")
    setD.add(10)
    setD.add(20)
    print("After add \(setD.size)")
}

testLinkedListSet()
testBSTSet()
